ALTER TABLE players ADD COLUMN IF NOT EXISTS total_clicks INTEGER DEFAULT 0;
ALTER TABLE players ADD COLUMN IF NOT EXISTS total_visits INTEGER DEFAULT 0;
ALTER TABLE players ADD COLUMN IF NOT EXISTS last_visit TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

CREATE TABLE IF NOT EXISTS cars (
    id SERIAL PRIMARY KEY,
    player_id INTEGER NOT NULL,
    car_type INTEGER NOT NULL,
    count INTEGER DEFAULT 1,
    UNIQUE(player_id, car_type)
);

CREATE INDEX IF NOT EXISTS idx_cars_player ON cars(player_id);